version: '3'

services:
  web:
    container_name: ${APP_NAME}_web
    build:
      context: ./docker/web
    ports:
      - 9000:80
    volumes:
      - ./:/var/www/html

  cache:
    container_name: ${APP_NAME}_cache
    build:
      context: ./docker/cache
    ports:
        - 63790:6379
